import type { Metadata } from "next";
import { MobileNav } from "@/components/mobile/mobile-nav";
import { SidebarMain } from "@/components/sidebar/sidebar";
import { SiteHeader } from "@/components/sidebar/sidebar-header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
	title: "Dashboard",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function Layout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<div className="min-h-svh overflow-x-hidden [--bottom-nav-height:4.5rem] [--header-height:calc(--spacing(14))]">
			<SidebarProvider className="flex flex-col">
				<div className="hidden md:block">
					<SiteHeader />
				</div>
				<div className="flex flex-1">
					<SidebarMain />
					<SidebarInset className="max-w-full overflow-x-hidden p-4 pb-[calc(var(--bottom-nav-height)+1rem)] md:pb-4">
						{children}
					</SidebarInset>
				</div>
				<MobileNav />
			</SidebarProvider>
		</div>
	);
}
